### PR TITLE
Fix build with XCode 10

### LINKED ISSUE #11: Cannot build master on OS X 10.14
This line breaks the compilation with clang

https://github.com/JuliaLang/libosxunwind/blob/e49098e7cfb262e8bba92c4accd497db03ca79dd/Makefile#L14

to use `stdc++` on OS X, it should be `-stdlib=libstdc++` rather than `lstdc++`

Ref: https://github.com/spack/spack/issues/5942

#### versions

- `clang`: Apple LLVM version 10.0.0 (clang-1000.11.45.2)
- OS X: 10.14 (18A391)

I was able to build `master` branch on the same Mac, but it breaks somehow after I upgrade to Mojave.

### PR DESCRIPTION
**Pull request by iamed2**
See https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes?language=objc

Fixes #11

### CODE REVIEW

**Comment by Roger-luo** [comment]
I was considering whether this breaks the build on other platforms?

**Comment by iamed2** [comment]
I don't know if it's right either but I need it and Keno said it seemed fine on Slack

**Comment by ararslan** [comment]
> I was wondering whether this breaks the build on other platforms?

It shouldn't, since this repository is specific to macOS. On other platforms we use libunwind.

**Comment by ararslan** [comment]
Unless you mean other macOS/Xcode versions. It would likely be worthwhile to condition on the version being used, since this wasn't a problem until recently. You should be able to use Apple's C macros to get versions.

**Comment by iamed2** [comment]
XCode 8+ will support this solution for sure, so we could condition on that, but I'm not sure what the macros are to check those things

**Comment by ararslan** [comment]
I think this should do it.
```c
#include <AvailabilityMacros.h>

#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_12
// stuff using -stdlib=libstdc++
#else
// stuff using -lstdc++
#endif
```

**Comment by ararslan** [comment]
Each version of Xcode CLT has a minimum and maximum macOS version it supports, so it seems roughly safe to condition on the macOS version if we set it recent enough, even though it isn't a perfect check.

**Pull request closed without merging**
